### ISSUE TITLE
[공통 뷰] 재사용 가능성을 고려해서 collectionView를 재사용할 수 있도록 구현

### ISSUE THREAD

**Issue by letusHyun** [IF-TG/iOS#114]
## 📖 참고 자료

<img src="https://github.com/IF-TG/iOS/assets/108918481/a7ba3d23-492b-4317-88e4-6eabe1b90540" width="200" /> 

- 그림에서 점선의 화면을 재사용할 수 있도록 구현하기

## 📱 화면 네이밍:
- ViewController
- View

### UI

- [ ]  커스텀 collectionView를 정의하고, layout, headerView, cell의 contentView를 커스텀할 수 있도록 구현하기

### Feature

- [ ]  todo1
- [ ]  todo2

**Comment by SHcommit** [comment]
- 분리완료 #121
