### ISSUE TITLE
[Bug] 이미지뷰의 contentMode가 제대로 설정되지 않는 문제

### ISSUE THREAD

**Issue by letusHyun** [IF-TG/iOS#120]
## Description
BaseDestinationView의 imageType을 default로 설정 시, contentMode가 설정한 대로 적용되지 않습니다.

## 스크린샷이나, 링크, 사진을 첨부해주세요.

<img width="327" alt="image" src="https://github.com/IF-TG/iOS/assets/108918481/d3601df3-38f2-4c3c-a4c7-44d8c8bbb634">

## 버그가 나는 코드를 보여주세요.

![Image](https://github.com/IF-TG/iOS/assets/108918481/2af48084-76f1-47d0-9768-f67c6d742534)
![Image](https://github.com/IF-TG/iOS/assets/108918481/bf83fcf3-e143-4c2a-a91a-be963d66b1f0)
![Image](https://github.com/IF-TG/iOS/assets/108918481/52d83b7a-6777-4e4e-a32d-43875a4506a6)

TDCell에서 BaseDestinationView를 생성할 때, imageViewType을 default로 설정했기 때문에, imageView의 contentMode가 scaleAspectFill이 나올것을 기대했습니다. 하지만 View Hierarchy로 확인해보니 scaleToFill로 적용되어 있습니다.

![Image](https://github.com/IF-TG/iOS/assets/108918481/1e17dd26-bb9f-4a35-b067-cc8627425eda)

**Comment by SHcommit** [comment]
![image](https://github.com/IF-TG/iOS/assets/96910404/2927eeeb-0fd0-4ee0-8fdc-1e9114814939)

저도 뷰 계층구조 봤는데 asfect fill로 된것 같은데요?..?

![image](https://github.com/IF-TG/iOS/assets/96910404/4dd7c15d-88ad-4310-b425-938a6bc7b45c)

**Comment by letusHyun** [comment]
이후에 문제 수정했는데 closed를 안했었네요..! 문제원인은 내부에 contentMode가 scaleToFill로 되어있어서 해결방법으로 contentMode를 수정했었습니다.
