### ISSUE TITLE
[Bug] 다크모드 시, color가 동일하지 않는 UI를 발견했습니다.

### ISSUE THREAD

**Issue by letusHyun** [IF-TG/iOS#122]
## Description
다크모드 시, color가 동일하지 않는 UI를 발견했습니다.

## 스크린샷이나, 링크, 사진을 첨부해주세요.

<img width="250" alt="image" src="https://github.com/IF-TG/iOS/assets/108918481/ea919677-bca6-4676-bcd3-9c135c400dee">

다크모드의 경우, 스크롤 시에 탭바의 color가 검정색으로 변하는데, 스크롤중 맨 밑에 닿아 스크롤이 완료되면 비로소 탭바의 color가 흰색으로 변경되는 문제점이 있습니다. 당장은 라이트모드만 지원할 예정이라, 탭바의 color문제를 해결해야 할 것 같습니다.

</br></br>

--- 
<img width="250" alt="image" src="https://github.com/IF-TG/iOS/assets/108918481/e60bbaf9-5005-4c34-bbef-558313694bae">

라이트모드와 다크모드에 따라 탭바 아이콘의 color가 변경되는데, 하나의 color로 통합해야할 것 같습니다.

## TODO

- [x] 다크모드일 때, 스크롤 중일때와, 스크롤 완료일때의 탭바 color 통일시키기

- [x] 다크모드와 라이트모드 상관없이 탭바 icon color 고정시키기

**Comment by SHcommit** [comment]
확인했습니다 : )

**Comment by SHcommit** [comment]
수정 완료했습니다. #130
