### ISSUE TITLE
[Common] InnerRoundRectReusableView 객체의 shadow를 type에 맞게 정의

### ISSUE THREAD

**Issue by letusHyun** [IF-TG/iOS#127]
## TODO

section의 backgroundView인 InnerRoundRectReusableView는 기본적인 UI가 같기 때문에 검색 detail화면에서도 재사용했습니다. 유일한 차이점이 있다면, 아래 그림처럼 shadow의 y값이 다릅니다.
- InnerRoundRectReusableView객체를 enum type에 따라서 shadow를 정의하면 좋을 것 같습니다!

<img src="https://github.com/IF-TG/iOS/assets/108918481/7db52133-bae3-4b9e-b312-95d84a91e276" width="800" /> 

<img src="https://github.com/IF-TG/iOS/assets/108918481/32c1f06e-e90e-4f00-9ae7-3e83aaa3d096f" width="350">|<img src="https://github.com/IF-TG/iOS/assets/108918481/0cf1cf9c-3971-468a-8c28-8ba4988e71bf" width="350">
|:-:|:-:|
|`피드 section view의 shadow`|`검색 detail section view shadow`|

</br>

현재 저는 검색 상세화면에서 
![Image](https://github.com/IF-TG/iOS/assets/108918481/ca18f053-c55a-4118-bc4b-65aa725e2320)
![Image](https://github.com/IF-TG/iOS/assets/108918481/b677ba4f-2ea9-4c58-9f37-c6bfccddff77)
이렇게 InnerRoundRectReusableView객체를 적용하고 있습니다.

## 📱 화면 네이밍:
- InnerRoundRectReusableView

### UI

- [x]  InnerRoundRectReusableView의 shadow를 2가지 타입으로 정의하기
- [x]  이를 기반으로 두 화면에 적용하기

### 궁금한 점
- 프로그래머가 InnerRoundRectReusableView를 생성자를 통해 객체 생성하지 않기 때문에, enum type에 맞게 정의가 가능한지 의문입니다. 안된다면, SuperInnerRoundRectReusableView를 상속하는 SubInnerRoundRectReusableView를 각각 정의해야 할 것 같습니다!

**Comment by SHcommit** [comment]
- 리빌딩 완료!! #132

**Comment by letusHyun** [comment]
감사합니다!
