### ISSUE TITLE
[Fix] iOS 13 mini target 15.5 버전 Feed화면의 포스트가 보이지 않는 문제 해결했습니다.

### ISSUE THREAD

**Issue by SHcommit** [IF-TG/iOS#147]
## Description

문제: iOS 13 mini에서 피드화면의 포스트가 보이지 않는 문제 발견

특정 기기에서 feed 탭의 postView 포지션이 모호해서 레이아웃이 제대로 잡히지 않는 문제가 발생되었습니다.

## 스크린샷이나, 링크, 사진을 첨부해주세요.

<img src="https://github.com/IF-TG/iOS/assets/96910404/9c27d7f4-8d5d-41d4-bd08-c18dc70922f8" width="250">|<img src="https://github.com/IF-TG/iOS/assets/96910404/69867ec2-4325-4343-a98d-7a0942a2f175" width="250">|
|:-:|:-:|
|`iOS  13 mini, target: iOS 15.5`|`iOS  13 mini 해결`|

### 1. Code snippet

https://github.com/IF-TG/iOS/blob/76fdd547e23cb3488e58048e42d7485c690f852d/travelPlan/Source/Feature/Feed/ViewController/FeedPostViewController.swift#L48-L55

문제가 아니지만 문제는 이 코드에 있었습니다.

### 2. Code snippet

https://github.com/IF-TG/iOS/blob/76fdd547e23cb3488e58048e42d7485c690f852d/travelPlan/Source/Feature/Feed/ViewController/FeedPostViewController.swift#L58-L73

그리고 또 다른 문제의 코드입니다.

다른 기기에서는 잘 동작됬으나... 신기하네요.

![ㄴㄴㄴㄴ](https://github.com/IF-TG/iOS/assets/96910404/906136cc-662e-44f1-8e7d-74b71094e5c8)

실제 화면의 구성은 카테고리부분은 뷰 그리고 포스트가 나오는 영역은 PageViewController를 사용했습니다. 그래서 위에 언급한 code snippet은 UIViewController타입의 뷰에 포스트가 보여지는 뷰를 추가한 것입니다.

이때 UIViewController는 loadView시점에 view라는 프로퍼티의 초기화를 직접 할 수 있었고, post가 담긴 postView를 초기화 했습니다. 그럼 뷰컨의 뷰의 자식뷰로 추가후 오토레이아웃을 잡지 않아도 됩니다....

Code snippet 2를 보면, 여기서도 문제가 있을 수 있다는 것을 알 게 되었습니다... PostView는 결국 뷰컨트롤러의 뷰나 서브뷰로 대체해야하는데, 이때 바인딩을 너무 일찍해서 뷰가 화면에 로드되기 전 init시점에 바인딩을 했고, 이는 뷰가 화면에 포지션 잡히기 전에 데이터를 받아서 갱신만 하게 될 수 있다는 것입니다..

### 해결

![image](https://github.com/IF-TG/iOS/assets/96910404/fe43a72f-01cb-45bc-a8ee-016cd0480114)

음.. 다른 기기는되는데,, 그리고 신기한 것은..

```
...
override func viewDidLoad() {
  super.viewDidLoad()
  view.addSubview(postView)
  postView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
}
```

이렇게 리사이징도 안된다는것...

음,,,,,,

## ETC

- 이전에 알게된 개념
  reloadData는 dispatchqueue.main인 main thead에서 실행 해야 바로 적용된다..

**Comment by letusHyun** [comment]
바인드 시점은 UI 레이아웃이 완전히 잡힌 후에 해줘야 되는군요..

**Comment by SHcommit** [comment]
네 일반적으로 그게 좋은것 같습니다,,,,,
