### ISSUE TITLE
[Layout issue] Feed의 PostViewCell에서 컴포넌트의 레이블 길이가 애매모호합니다.

### ISSUE THREAD

**Issue by SHcommit** [IF-TG/iOS#15]
## Description
Feed의 PostViewCell에서 PostHeaderSubInfoView에서 Feed Layout issue가 발생합니다.

## 스크린샷

- layout issue가 발생되는 PostViewCell

<img width="909" alt="이슈 1" src="https://github.com/IF-TG/iOS/assets/96910404/6d8d3158-f1ad-4291-83c9-48d94189d9ca">

- PostHeaderSubInfoView의 컴포넌트들 레이아웃이 모호합니다.

<img width="334" alt="이슈 상황" src="https://github.com/IF-TG/iOS/assets/96910404/2d5a47d9-8cd1-4cb0-bd31-16a5e2e44b96">

--- 

<img width="325" alt="이슈 안나는 경우" src="https://github.com/IF-TG/iOS/assets/96910404/e29e70c7-0780-4e51-8f0b-2af2e87cdd0b">

일반적으로 각각의 컴포넌트가 특정 width를 넘지 않도록 제약 조건을 걸었습니다.

<img width="327" alt="이슈나는 경우" src="https://github.com/IF-TG/iOS/assets/96910404/bacc908c-e12e-45dc-8705-3c2db7c5fead">

하지만 특정 Label이 지정된 width를 넘는 경우 위와 같은 Layout issue가 발생합니다. 

## 버그가 나는 코드를 보여주세요.

https://github.com/IF-TG/iOS/blob/59aa6c4fe28ebf9d88cead24b3fb5842fe502e3e/travelPlan/Source/Feature/Feed/View/PostView/PostCell/PostHeaderView/PostHeaderSubInfoView.swift#L120-L178

## Etc

- userNameLabel.width.constraint(lessThanOrEqualToConstant:) 이 함수를 사용해서 뷰의 최소 ~ equal 값을 지정해 주었는데, userNameLabel의 trailing을 또 auto layout의 leading으로 연결되어있어서 이러한 에러가 나는지 의문입니다.

**Comment by letusHyun** [comment]
혹시 Content hugging이나 Content compression 설정해보셨어요?

**Comment by SHcommit** [comment]
그 설정들을 추가해볼게요.
