### ISSUE TITLE
[Question] FavoriteViewController의 네비게이션 바 bottom edge one unit gray line 문제

### ISSUE THREAD

**Issue by SHcommit** [IF-TG/iOS#20]
## Description

- OneUnitHeightLine의 함수 추가 ( view.safeAreaLayoutGuide.topAnchor를 토대로 선 그립니다.)

FavoriteViewController의 navigation bar's bottom edge one unit gray line 레이아웃 잡을 때 문제가 있습니다.

https://github.com/IF-TG/iOS/blob/e6c1f74b0d6faa50e6625e5b7620f05b4be2cc14/travelPlan/Source/Common/View/OneUnitHeightLine.swift#L72-L89

위의 함수에서 setConstraint(fromSuperView:) 매개변수를 네비게이션 바로 했을 때의 경우입니다.

navigation Bar의 bottom edge에 높이 1, navigationBar의 bottom constant: -5인  gray line을 설정했을 경우

<img width="366" alt="oneUnitGrayLine추가한 경우 spacing -5" src="https://github.com/IF-TG/iOS/assets/96910404/86766efc-8f09-43d1-a6f8-fe0e47644d40">

위의 사진과 같이 navigationBar의 bottomAnchor constant -5 지점에 네비게이션 바 영역 구분하기 위한 one unit gray line이 만들어집니다.  (지금은 그 line을 선택해서 파란색으로 보여집니다.)

이때 제가 기존에 구현했던 초기 방식은 navigationController?.navigationBar.addSubview() 함수에 line ( OneUnitHeightLine 타입 )의 인스턴스를 추가했습니다. 그리고 line의 레이아웃은 navigationBar의 bottom -5로 지정을 했습니다.

이럴 경우 발생될 문제는 navigationBar의 height가 subview의 레이아웃까지 포함해서 커지는게 아니라 navigationBar의 높이는 시스템에서 부여된 그대로였습니다.  원래 커스텀 뷰 안에 있는 subview의 오토 레이아웃을 잡을 경우 커스텀 뷰의 높이를 명시적으로 지정하지 않으면 subview의 최대 높이만큼 감싸져야 하는데.. 제가 해봤는데 그게 안됩니다. 시스템에서 navigationBar의 height를 지정하나 봅니다. 물론 navigationBar의 height 지정을 안했는데, 네비바의 높이 지정하는 방법이 까다로운것 같습니다....

<img width="443" alt="원래 네비게이션 바 크기" src="https://github.com/IF-TG/iOS/assets/96910404/3750a46a-56a2-4696-a826-5130733d23c8">

뒤에 보이는 파란 영역이 navigationBar 영역입니다.... (**subView인 gray line은 navigationBar의 height로 추가되지 않았습니다.**)

이 상태로 이제 FavoriteViewController의 subview에 대한 layout 지정을 FavoriteViewController's view 의 safeAreaLayoutGuide로 topAnchor를 설정했을 경우 (gray line을 제외한) navigationBar의 하단 부분에서부터 적용되지만, gray line을 포함한 높이가 되지 않기에, navigationBar.addSubview로 navigaitonBar에 대한 subview의 autoLayout 잡는 방법은 좋지 않겠다고 생각했습니다. 

NavigationBar의 바로 아래에 tableView가 있는데 naiviBar의 진짜 높이는 grayLine을 포함하지 않았기 때문에,, tableView의 레이아웃 지정이 까다롭습니다.

이 경우에 tableView의 topAnchor 지정은 tableView.safeAreaLayoutGuide.topAnchor.constraint()의 constant를 line의 높이까지 포함한 5 + 1로 설정해야 했습니다...

그래서 이번엔 다른 경우를 시도해봤습니다. fromSuperView로 navigationController's view를 super view로 gray line을 subview로 시도했지만, 이번에는 스크롤을 할 때만 선이 보여지게 되었습니다.

---

현재 대안으로는 FavoriteViewController의 view.safeAreaLayoutGuide.topAnchor의 constant로 5를 설정하여 뷰의 최상단에 line을 추가하고, 그 아래에 view의 subview를 추가하는 것입니다. 이때 line아래에 추가될 view의 topAnchor는 line의 bottomAnchor가 되야합니다.

OneUnitHeightLine 클래스에 새로운 함수를 추가했습니다. 이 함수는 네비바의 edge를 gray line으로 그리는 경우입니다.

https://github.com/IF-TG/iOS/blob/e8f18638b943f3113df0bed81c2ccd7d4a76f2e6/travelPlan/Source/Common/View/OneUnitHeightLine.swift#L98-L114

더 효율적인 대안 있으면 좋을 것 같습니다. 

## TODO

- [ ] NavigationBar의 bottom edge에 navigationBar로부터 spacing -5인 constant에 높이 1 짜리 gray line( width: 세로 화면일때 width길이)인 경우와 커스텀 back button을 기본 상속하는 커스텀 네비 관련 기능 구현해야 합니다.

**Comment by letusHyun** [comment]
가장 좋은 방법은 navigationBar에 line을 추가했을 때 safeAreaLayoutGuide가 잘 잡히는 것인데, 이 방법이 안된다니 아쉽네요.
저도 navigationController를 더 공부해서 해결책을 찾아보겠습니다.

**Comment by SHcommit** [comment]
네 같이 연구해봐도 좋을 주제 같습니다 +_+

**Comment by SHcommit** [comment]
https://stackoverflow.com/questions/35680853/custom-height-for-uinavigationbar-or-alternative-of-uinavigationbar

시스템에서 제공하는 기본 네비바 height를 변경할 수는 없다고 합니다.

**Comment by SHcommit** [comment]
https://developer.apple.com/forums/thread/88202#274620 어?? 이렇게 네비 조정되나 확인해봐야겠습니다. 이러면 safeAreaLayoutGuide크기도 변경됬으면 좋겠네요.

추가적으로 기본적으로 appearance 설정하면 네비바에 기본 gray line이 주어지는 것 같습니다. 아래 설정만 했는데 선이,, +_+?! ( 다나까 가운데 선)
![image](https://github.com/IF-TG/iOS/assets/96910404/6515164f-6dda-4c29-843c-9b7f338da104)

**Comment by letusHyun** [comment]
navigationBar의 subView인 grayLine을 오토레이아웃을 통해 추가했다면, self.view와 navigationBar의 오토레이아웃 설정을 해보시는건 어떤가요?

if let navigationBar = self.navigationController?.navigationBar {
    self.view.snp.makeConstraints { 
        $0.top.equalTo(navigationBar.snp.bottom)
        // 다른 제약 조건들도 여기에 추가...
    }
}

이런식으로 self.view의 top을 navigationBar의 bottom과 오토레이아웃 설정을 해주면 어떨까 합니다.

**Comment by SHcommit** [comment]
저경우에 navigationBar에 추가한 subview의 bottom이 인식이 안됩니다. 네비바 자체의 높이가 44로 고정이 되어있기 때문에 
![image](https://github.com/IF-TG/iOS/assets/96910404/b09114a4-74ac-4f36-844d-c60c7e829953)

이 사진처럼 44 + 6으로 커스텀하는 경우에도 safeAreaLayoutGuide의 높이도 변경이 안되고,

위 답변 오토레이아웃의 경우 navigationController.navigationBar 뷰는 viewController's view에 subview로 등록이 안되어있어서 오토레이아웃이 안됩니다.

**Comment by letusHyun** [comment]
아하 내비바의 height가 고정이 되어있어서 해결이 안되는군요..
