### ISSUE TITLE
[Refactor] ViewModelProtocols의 내부를 리펙터링했습니다 +_+

### ISSUE THREAD

**Issue by SHcommit** [IF-TG/iOS#22]
## Description

ViewModel에 Input/Output binding을 구현할 떄 자주 사용되는 코드를 아래 코드와 같이 제가 추천한 코드의 기능을 변경하고자 합니다.

https://github.com/IF-TG/iOS/blob/4b285b5d4d007805f12e5ef8ac7d3831646f9464/travelPlan/Source/Common/Protocol/ViewModelProtocols.swift#L8-L27

## Comments

![image](https://github.com/IF-TG/iOS/assets/96910404/eefb309f-5c84-45a3-840f-2e6b7e9ffcde)

VM의 Input, ViewModel의 State에 대한 선언과 관리를 위해 더 좋은 방식으로 리펙터링을 통해 제안해주셨기에

![image](https://github.com/IF-TG/iOS/assets/96910404/9322e504-8b35-4ed8-ba9f-30e794a871cf)

기존에 선언했던 코드에 대해 곰곰이 생각을 해봤습니다. 기존의 제 ViewModelProtocols의 방식의 몇가지 불편함이나 문제점을 저 또한 살짝 감지하고 있었습니다.

Input/Output binding은 특정 ViewModel과 관련이 있고 그외에 다른 VM 에서는 잘 사용하지 않을 Input, State, Output 입니다. ViewModel 객체 안에 넣어서 관리하는게 차라리 "특정ViewModel.Input" 이런식으로 호출하지 않는 이상 왠만한 코드 타이핑 시 자동완성에도 보일 일이 없어 더 원활하게 개발을 할 수 있다는 의견에 동의했습니다.

VM에 들어오는 Input 그리고 VM 에서 발생되는 Output이 VM 의 내부에 선언하는 게 좋은 방식인 것 같습니다. 어떻게하면 효율적으로 선언하고 편하게 사용할지 생각을 해봤고 새롭게 리펙터링 해봤습니다. +_+

___

https://github.com/IF-TG/iOS/blob/3c2e1c692fa6706a827c9154107ba40a565dff61/travelPlan/Source/Common/Protocol/ViewModelProtocols.swift#L10-L49

### 우선 ViewModelProtocols의 변화입니다.

중복되는 protocol을 더 작은 단위로 분리했습니다. 

ViewBindAssociatedType 프로토콜은 뷰에 bind에 관련된 associatedtype입니다. 이는 아래의 두 프로토콜에서 채택합니다.

- ViewBindCase: ViewBindAssociatedType

- ViewModelAssociatedType: ViewBindAssociatedType  
  

###  ViewBindCase 사용

ViewBindCase의 경우 custom view나, viewController 에서 VM과 Input/Output binding을 준수할 경우 편하게 선언해서 사용할 수 있습니다.

https://github.com/IF-TG/iOS/blob/3c2e1c692fa6706a827c9154107ba40a565dff61/travelPlan/Source/Feature/Authentication/Login/ViewController/LoginViewController.swift#L35-L76

채팅방에서 알려주셨던 것과 같이 typealias를 통해 쉽게 사용할 수 있도록 했고 VM.associatedtype인스턴스 를 typealias로 지정하여 접근하도록 했습니다.

- ViewBindCase에서 handleError(_:) 잘 사용하지 않을까봐 protocol's extension으로 함수 구현만하고 원할때마다 handleError(_:)를 정의해서 구현할까도 생각했는데 비효율인 것 같아서 그냥 사용하지 않을 경우 선언 후 괄호만 씌워 기본 구현하면 됩니다.

###  ViewModelAssociatedType 사용 방법

이 경우에는 위에 ViewBindCase 처럼  사용할 수 있지만 그럼에도 Input, State, Error 각각의 case, property가 많아질 수 있기에 따로 extension으로 확장할 수 있도록, 이때 기존에 선언했던 ViewBindAssociatedType를  코드를 확장한 ViewModelAssociatedType를 준수하면 됩니다.

https://github.com/IF-TG/iOS/blob/3c2e1c692fa6706a827c9154107ba40a565dff61/travelPlan/Source/Feature/Authentication/Login/Extension/LoginViewModel%2BAssociatedtype.swift#L10-L28

### ViewModelCase 사용 방법

마지막으로 ViewModelCase입니다. 이전에 위에서 extension으로 선언했기에 transform()함수와 관련 opeator chaining 등등의 처리를 하면 됩니다.

https://github.com/IF-TG/iOS/blob/3c2e1c692fa6706a827c9154107ba40a565dff61/travelPlan/Source/Feature/Authentication/Login/ViewModel/LoginViewModel.swift#L10C1-L42

## 결론

- vm의 AssociatedType은 extension (ViewModelAssociatedtype으로 ViewModel에서의 Input, Output, State를 정의합니다.
- ViewController는 채택안해도되지만 사용하기 쉽게 ViewBindCase 
- vm은 ViewModelCase 채택

**Comment by SHcommit** [comment]
<img width="319" alt="image" src="https://github.com/IF-TG/iOS/assets/96910404/196b9937-3bbe-4280-80b3-8e9d08aafce8">

두번째 함수의 input객체 안 init시점에 기본 값으로 할당해도 된다는 것을 제가 생각하지 못했었는데.. 석현이 형이 말해준 이  방법이 현재로 가장 효율적인 코드 같습니다.

1. Input iniit을 정의할 때 기본 값들을 정의한다.

![image](https://github.com/IF-TG/iOS/assets/96910404/ed380837-b369-4f26-ae0b-cc0b91401025)


2. 이때 Combine cocoa에서 사용될 수 있는 버튼이나 텍스트필드의 changed등의 퍼블리셔를 제외한 appear,viewDidLoad등은 PassthroughSubject로 한 후 기본 값을 대입한다. 


3. VC의 input 인스턴스 생성, 이슈 그림 2번째 처럼 input. appear.send()로 vm에게 input event를 발송한다.

<img width="650" alt="image" src="https://github.com/IF-TG/iOS/assets/96910404/32d532d6-781f-43b7-a963-0db10a96c36a">

이때 VC에서 input 인스턴스 선언 방법은 두 가지가 있는데, lazy var와 Input! 타입으로 선언 후 bind()내부에서 초기화 하는 방법인데 후자의 경우 혹시모를 실수가 있기에 lazy var를 사용하기로 했습니다.

**Comment by letusHyun** [comment]
확인했습니다 :)
