### ISSUE TITLE
[피드] 여행 후기 홈 → 썸네일 홈 화면 UI

### ISSUE THREAD

**Issue by letusHyun** [IF-TG/iOS#43]
## 📖 참고 자료
<img src="https://github.com/IF-TG/iOS/assets/108918481/c186e270-dd2f-409a-b546-26e0a0cd7fe0" width="200"/>

## 📱 화면 네이밍:

- FeedViewController

### UI

- [x] 여가 로고
- [x] 여행 후기 검색 버튼
- [x] 여행 후기 알림 버튼
- [x] 여행 카테고리 목록 뷰 ( 가로 스크롤 ) 
- [x] 여행 카테고리 목록 뷰 애니메이션 및 선택시 icon 변화, icon 추가
- [x] 여행 카테고리 목록 별 여행 후기 화면
- [x] 여행 카테고리 상세 메뉴 뷰
- [x] 사용자 여행 후기 thumbnail cell
- [x] 사용자 여행 후기 thumbnail cell header ( 프로필, 여행 후기 제목, 올린시간, 여행 기간, 포스트 관련 설정 버튼 )
- [x] 사용자 여행 후기 thumbnail cell content영역 ( 이미지, 글 )
- [x] 사용자 여행 후기 thumbnail cell footer ( 하트 버튼, 하트 개수, 댓글 icon, 댓글 개수, 공유 버튼) 
- [x] 리뷰 작성 버튼
- [x] 여행 메인 카테고리별 상세 테마 정렬, 트렌드 버튼 추가
- [x] 여행 메인카테고리별 상세 테마 정렬이나 filter버튼 클릭 시 관련된 세부카테고리 바텀시트로 전환
- [x] 피드 스크롤할때 스크롤바 없애기 (거슬림)

### Rebuild
- [x] 기존 여행 카테고리 별 여행 후기 화면을 cell로 했는데, 재사용 문제로 인해 page control로 리빌딩 
- [x] 기존 여행 카테고리 상세 메뉴 뷰를 collectionview header로 지정했는데, 검색 탭에서도 사용되기 때문에 상위 타입으로 분리, 자식의 경우 collectionview 오버라이드해서 헤더 추가하는 방법으로 리빌딩
- [x] 기존 여행 카테고리 상세 메뉴 뷰 순위 전체, 정렬 두 개의 뷰 위치 변화 및 분류, 최신순으로 네이밍 변경 및 관련 model 리빌딩
- [x] 여행 포스트 화면 compositional layout도입 -> section내부 쉐도우, 둥근 배경 추가
- [x] 여행 포스트 화면 사용자 후기 thumbnail cell 내부 거의 피그마 UI업데이트되서 다시 다 새로 constant 변경해야합니다.
- [ ] 석현이형 compositoinal layout 관련 protocol 추가시 이를 기반으로 PostCollectionView 컴포지셔널 layout 객체 따로 빼서 재사용하기 쉽게 리빌딩

### Knowledge

**Comment by SHcommit** [comment]
- 구현 완료 #133
