### ISSUE TITLE
[피드] 여행 상세 후기 → 그만보기 및 신고 화면

### ISSUE THREAD

**Issue by letusHyun** [IF-TG/iOS#44]
## 📖 참고 자료

<img src="https://github.com/IF-TG/iOS/assets/96910404/2101e2af-e789-4175-88e2-bb54b8d9c894" width="350">|<img width="350" alt="image" src="https://github.com/IF-TG/iOS/assets/96910404/cf400979-1c51-41c5-8f82-518526f69b66">|<img width="350" alt="image" src="https://github.com/IF-TG/iOS/assets/96910404/6e753fd3-403a-4611-819c-0265c225347b">|
|:-:|:-:|:-:|
|`여행 리뷰 그만보기 화면`|`여행 리뷰 차단 화면`| `여행 리뷰 신고 화면`| 

## 📱 화면 네이밍:

- VC
- View

### UI

- [x]  todo1
- [x]  todo2

### Feature

- [x]  todo1
- [x]  todo2

### Preknowledge

-

**Comment by SHcommit** [comment]
Closed #199
