### ISSUE TITLE
[피드] 여행 후기 홈 → 썸네일 공유 화면

### ISSUE THREAD

**Issue by letusHyun** [IF-TG/iOS#75]
<img src="https://github.com/IF-TG/iOS/assets/108918481/fba55fac-9344-4c12-b76c-1bdcc6487fc0" width="350">|<img width="350" alt="image" src="https://github.com/IF-TG/iOS/assets/108918481/915d7862-a360-4011-a4a1-96a7ff8ff60a">|
|:-:|:-:|
|`스와이프 전`|`스와이프 후`| 

## 📱 화면 네이밍:

- VC
- View

### UI

- [x]  todo1
- [x]  todo2

### Feature

- [x]  todo1
- [x]  todo2

### Preknowledge

-

**Comment by SHcommit** [comment]
- Closed #246 구현 완료!
