### ISSUE TITLE
[피드] 여행 상세 후기

### ISSUE THREAD

**Issue by letusHyun** [IF-TG/iOS#76]
<img src="https://github.com/IF-TG/iOS/assets/108918481/a6c42b3f-a546-46b3-a9d2-782525ac7860" width="250" />

- 게시글, 댓글, 댓글 입력

## 📱 화면 네이밍:

- PostDetailVIewController
- PostDetail*

### UI

- [x]  상세 후기 description 영역
- [x]  상세 후기 내용 영역
- [x]  상세 후기 댓글 영역
- [x] 하트및 댓글개수, 공유 영역
- [x] comment input accessory 뷰
- [ ] 삭제 기능

**Comment by SHcommit** [comment]
구현 완료 #148
