### ISSUE TITLE
[피드] 여행 상세 후기 → 카테고리 화면

### ISSUE THREAD

**Issue by letusHyun** [IF-TG/iOS#77]
<img src="https://github.com/IF-TG/iOS/assets/108918481/e9148c9f-3dbc-4eb3-8d61-8d7fbcecd14f" width="250" />

## 📱 화면 네이밍:

- VC
- View

### UI

- [x]  todo1
- [x]  todo2

### Feature

- [x]  todo1
- [x]  todo2

### Preknowledge

-

**Comment by SHcommit** [comment]
- Closed #200
