### ISSUE TITLE
[피드] 리뷰 테마 설정 화면

### ISSUE THREAD

**Issue by letusHyun** [IF-TG/iOS#84]
<img src="https://github.com/IF-TG/iOS/assets/108918481/279c9673-86dd-4064-abab-c36e67b46bd7" width="350">|<img width="350" alt="image" src="https://github.com/IF-TG/iOS/assets/108918481/1979d7cb-3e76-466f-ac61-8afbc8aa3ade">|
|:-:|:-:|
|`대분류에 따른 소분류`|`대분류에 따른 소분류`| 

## 📱 화면 네이밍:

- VC
- View

### UI

- [x]  todo1
- [x]  todo2

### Feature

- [x]  todo1
- [x]  todo2

### Preknowledge

-

**Comment by SHcommit** [comment]
- Closed #202
