### ISSUE TITLE
[피드] 사용자 갤러리 전체 사진 불러오기 화면

### ISSUE THREAD

**Issue by letusHyun** [IF-TG/iOS#86]
<img src="https://github.com/IF-TG/iOS/assets/108918481/0c89ec0e-5650-43eb-91de-3c6b9f57477f" width="350">|<img width="350" alt="image" src="https://github.com/IF-TG/iOS/assets/108918481/3a0b5f28-6b73-4f5c-8502-b46df5965c5a">|
|:-:|:-:|
|`앨범 화면`|`사진 선택`| 

## 📱 화면 네이밍:

- VC
- View

### UI

- [x]  todo1
- [x]  todo2

### Feature

- [x]  todo1
- [x]  todo2

### Preknowledge

-

**Comment by SHcommit** [comment]
- Closed #192 
- Closed #197
- Closed #188 
- etc...
