### ISSUE TITLE
[Bug] Feed에서 travel theme 카테고리 선택시 관련된 categoryDetailCell의 전환이 되지 않는 문제가 있습니다.

### ISSUE THREAD

**Issue by SHcommit** [IF-TG/iOS#92]
## Description
Feed에서 travel theme 카테고리 선택시 관련된 categoryDetailCell의 전환되지 않는 문제가 있습니다.

## 스크린샷이나, 링크, 사진을 첨부해주세요.

기존에는 정상 작동되었지만.. compositional layout으로 특정 section의 inset과 shadow, radius를 주기위해 컴포지셔널 레이아웃을 도입했고, 추가적으로 view render 때마다 자주 호출될 수 있는 뷰 라이프 싸이클 관련 메서드 layoutSubviews() 시점에 bounds를 기반으로 추가적으로 레이아웃하고 초기화 하는 메서드들을 분해하면서 위 문제가 발생됬습니다.. 재사용 관련 문제입니다. 화면 구현은 아래 ETC를 참고해주세요.

<img src="https://github.com/IF-TG/iOS/assets/96910404/164b66f4-0958-4357-b726-be9c155d05b8" width="350">|<img src="https://github.com/IF-TG/iOS/assets/96910404/a91f32bd-1eba-465a-814c-584eca506134" width="350">|
|:-:|:-:|
|`기존에 구현했던 정상 작동 화면`|`새로운 UI적용+컴포지셔널적용후 개선된 화면`|

## TODO

- [x] 여행 카테고리 테마 Cell 변경시 여행 테마에 따라 보여지는 화면 재사용 문제 해결하기

- [x] 3개의 컬랙션 뷰를 하나의 컬랙션뷰에 컴포지셔널로 구성했을 떄, 위 화면과 마찬가지로 재사용 문제가 발생될 것 같은데.. 디퍼블 공부 좀해보고, 우선 PageControl로 파랑 영역 정의해서 뷰컨으로 확실하게 관리하도록 리빌딩

## ETC 개선한 사항

<img src="https://github.com/IF-TG/iOS/assets/96910404/0c29178f-9aaf-4f8c-bedc-a5830c6b003b" width="350">|<img src="https://github.com/IF-TG/iOS/assets/96910404/878e721a-0042-4364-bd70-45a899952d08" width="350">|
|:-:|:-:|
|`화면`|`구조 설명용 화면`|

참고로 기존 왼쪽화면의 구성을 간단히 소개합니다.
1. 초록색 영역의 여행 카테고리 A 컬랙션 뷰 (가로 스크롤) 오토 레이아웃으로 지정합니다. 이때 세로 크기는 일정합니다. 
2. 위를 기반으로 파랑색 영역을 Cell로 하는 가로 스크롤이 되는 B컬랙션 뷰의 레이아웃을 지정합니다.
  이때 오토 레이아웃 시점을 호출하는 viewDidLoad함수 시점에는 B컬랙션 뷰의 bounds가 지정되지 않습니다. 

파랑 영역의 높이는 top status bar 높이 + 네비게이션 height + 초록색 높이 + safearea Bottom height를 UIScreen 크기에서 빼주면 됩니다. 이럼 명확하게 알 수 있는데 UIScreen.main이 depreciated되기 때문에.. 파랑색 B컬랙션뷰의 bounds가 오토레이아웃 시스템에 의해 계산된 후에 flow layout's itemSize를 파랑색 영역의 크기만큼 주어서 Cell을 잡고,

그 파랑 영역의 Cell 내부에 사용자의 포스트가 담는 포스트 컬랙션 뷰를 추가했었습니다. + 초기 초록색 영역에서 첫번째 Cell인 For you의 글자 크기를 구해 파랑색 영역의 스크롤 바 또한 새롭게 포지션 했었습니다.

### 코드 리빌딩으로 지금은 사라진 코드
![Image](https://github.com/IF-TG/iOS/assets/96910404/6c44d8b6-96d3-4a32-a8a2-5ae7a10b4ca0)

결국 파랑 색 영역의 크기를 명확하게 지정할 수 있기에 가장 쉬운 시점엔 layoutSubviews() 호출시점을 오버라이드해서 위와 같이 구성했습니다.

이 문제점은 자주 호출되는 layoutSubviews()에 레이아웃 코드를 작성하고 그 내부적으로 layoutIfNeedes()함수도 호출한다는 점입니다. + 아무런 조건 없이,, 

그래서 제거했습니다.

그리고 새롭게 개선된 피그마의 UI를 반영하기 위해 컴포지셔널도 도입해서 section과 컬랙션 뷰로부터 떨어지는 inset, shadow를 구현했습니다.

- 여기서는 A컬랙션 뷰의 내부 cell이 클릭되면, 그에맞게 주황 영역의 scrollBar도 해당 Cell영역으로 이동함과 동시에 여행 카테고리 텍스트의 크기에 맞게, 가운데 정렬이 되야 합니다. 그와 동시에 파랑색 영역의 Cell이 변경되고,  그 안의 컬랙션 뷰(여행 포스트)가 불러와집니다.

- 컴포지셔널 레이아웃을 도입한 컬랙션 뷰는 파랑색 영역의 Cell안에 정의된, 사용자 후기 보여주는 컬랙션 뷰입니다.

**Comment by letusHyun** [comment]
DiffableDataSource를 사용하면 재사용 문제가 해결될 수 있나요?

**Comment by SHcommit** [comment]
해결 안될 가능성이 있습니다..
