### ISSUE TITLE
[Question] 피드 화면에서 네비게이션으로 컨트롤러를 통해 다른 화면으로 전환할 때 네비바 흰색 유지되는 이슈

### ISSUE THREAD

**Issue by SHcommit** [IF-TG/iOS#97]
## 이전에 언급했던 문제:

- 피드에서 다른 화면갈 때 

navigationBar 색상이 네비게이션 전환 애니메이션 먹히지 않고 흰색으로 유지되는 이슈

<img src="https://github.com/IF-TG/iOS/assets/96910404/90cbb0f6-ab96-4a44-82f6-064bda01e11d" width="250">|<img src="https://github.com/IF-TG/iOS/assets/96910404/1053609d-4fbf-4288-a70e-7fa1406e69a7" width="250">|
|:-:|:-:|
|`화면 전환 시 이슈`|`네비+status bar영역에 백그라운드 뷰 추가로 해결`|

- 문제의 코드

![image](https://github.com/IF-TG/iOS/assets/96910404/ede40a18-9d38-4bb3-b103-cd8967205131)

유지되는 이유는 피드에서.. naviBar의 색상을 white로 했기 때문입니다. 

원래 네비게이션 바의 색을 지정하지 않으면, status bar 배경 색이 없다면 뷰컨.view.backgroundColor가 자연스레 적용됩니다. 

피드 뷰컨은 정말 이상하게,, 피드 뷰컨에서 view.backgroundColor = .white로 했을 때만 "_UIVisualEffectBackdropView"의 색상이 불투명색으로 변합니다. 네비게이션 바 영역, status bar 영역이 흰색이 적용이 되지 않습니다. 약간 어두운 회색이 적용됩니다. 그러나 뷰의 백그라운드를 핑크나 오랜지 등 다른 색으로 하면 적용이 잘 됩니다.... 네비게이션 바의 영역, status bar 또한 뷰컨의 뷰의 배경색에 적용된다는 뜻 입니다.

### view.backgroundColor = .white인 경우

![image](https://github.com/IF-TG/iOS/assets/96910404/23e8ec02-b153-4a68-bbd8-2b12b5707c82)

### view.backgroundColor = .orange인 경우

![image](https://github.com/IF-TG/iOS/assets/96910404/de5d69e4-d55b-46c6-9594-42f2bb8b54f9)

저기 네비바 + status bar영역의 비쥬얼 백그라운드 색이 오랜지로 적용 됩니다. 그러나 흰색은 안되고 불투명한 색이 적용됩니다.

그 외에 피드 뷰컨에서 뷰의 백그라운드 색을 오랜지색이나 핑크색으로 뷰의 백그라운드를 하면 비쥬얼 백그라운드 색도 자연스럽게 적용 됩니다. 뷰컨의 뷰 백그라운드 **색**을 **흰색으로 할 경우에만 흰색 적용이 안됩니다**.

naivgation appearance를 적용하면 화면전환되는 하위 coordinator's presenter에 의해 모든 네비게이션 영역에 적용되기에 자연스레 사라지는 애니메이션이 먹히지 않습니다.

그래서 지금은 흰색 백그라운드 뷰를 만들어서 네비게이션+status bar 영역에 추가했습니다. 
더 좋은 방법이 있을까요?

**Comment by letusHyun** [comment]
현재로써는 이 방법이 최선인 것 같아보입니다 :)
